environment:  
  matrix:
  - PROJECT_NAME: test-project-1
  - PROJECT_NAME: test-project-2
  
clone_script:
- cmd: git clone https://github.com/IlyaFinkelshteyn/%PROJECT_NAME% %APPVEYOR_BUILD_FOLDER%

build_script:
- cmd: powershell .\build.ps1
- sh: sudo build.sh
