environment:  
  matrix:
  - PROJECT_NAME: test-project-1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - PROJECT_NAME: test-project-1
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    
  - PROJECT_NAME: test-project-2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - PROJECT_NAME: test-project-2
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    
clone_script:
- cmd: git clone https://github.com/IlyaFinkelshteyn/%PROJECT_NAME% %APPVEYOR_BUILD_FOLDER%
- sh: git clone https://github.com/IlyaFinkelshteyn/$PROJECT_NAME $APPVEYOR_BUILD_FOLDER

build_script:
- cmd: powershell .\build.ps1
- sh: bash ./build.sh

for:
-
  matrix:
    except:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
  skip_commits:
    message: /ubuntu-only/

-
  matrix:
    except:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  skip_commits:
    message: /vs2017-only/
