environment:  
  matrix:
  - project_name: test-project-1
  - project_name: test-project-2
  
clone_script:
- cmd: git clone https://github.com/IlyaFinkelshteyn/%project_name%

build_script:
- cmd: powershell .\build.ps1
- sh: sudo build.sh
